In [1]:
import selenium
from selenium import webdriver
import pandas as pd
import zipfile

In [2]:
# Using Chrome to access web
driver = webdriver.Chrome()#path in bracket in alter way
# Open the website
driver.get('https://geodash.vpd.ca/opendata/')

In [3]:
checkboxes = []
checkboxes = driver.find_elements_by_name("agreeCheckbox")
checkboxes[0].click()

<ipython-input-3-5d89a80ef92c>:2: DeprecationWarning: find_elements_by_name is deprecated. Please use find_elements(by=By.NAME, value=name)=By.NAME, value=name) instead
  checkboxes = driver.find_elements_by_name("agreeCheckbox")

In [4]:
checkboxes2ndPageYear = []
checkboxes2ndPageYear = driver.find_elements_by_name("year")
checkboxes2ndPageYear[0].click()

<ipython-input-4-74cd42d719fa>:2: DeprecationWarning: find_elements_by_name is deprecated. Please use find_elements(by=By.NAME, value=name)=By.NAME, value=name) instead
  checkboxes2ndPageYear = driver.find_elements_by_name("year")

In [5]:
checkboxes2ndPageNeib = []
checkboxes2ndPageNeib = driver.find_elements_by_name("nhood")
checkboxes2ndPageNeib[0].click()

<ipython-input-5-04c3175201bc>:2: DeprecationWarning: find_elements_by_name is deprecated. Please use find_elements(by=By.NAME, value=name)=By.NAME, value=name) instead
  checkboxes2ndPageNeib = driver.find_elements_by_name("nhood")

In [6]:
clickkbox = []
clickkbox = driver.find_elements_by_name("click")
clickkbox[0].click()

<ipython-input-6-673d47642da5>:2: DeprecationWarning: find_elements_by_name is deprecated. Please use find_elements(by=By.NAME, value=name)=By.NAME, value=name) instead
  clickkbox = driver.find_elements_by_name("click")

In [31]:
#df = pd.read_csv('crimedata_csv_AllNeighbourhoods_AllYears.zip',compression = 'zip')

with zipfile.ZipFile("crimedata_csv_AllNeighbourhoods_AllYears.zip") as z:
    with z.open("crimedata_csv_AllNeighbourhoods_AllYears.csv") as f:
        df = pd.read_csv(f)
        print(df.head())

                 TYPE  YEAR  MONTH  DAY  HOUR  MINUTE    HUNDRED_BLOCK  \
0  Theft from Vehicle  2022      3   17    21       0  39XX W 17TH AVE
1  Theft from Vehicle  2010      4   29    20      30  39XX W 18TH AVE
2  Theft from Vehicle  2003     12   23    23       0  39XX W 18TH AVE
3  Theft from Vehicle  2004      6   15    19       0  39XX W 18TH AVE
4  Theft from Vehicle  2004      6   16    22       0  39XX W 18TH AVE

       NEIGHBOURHOOD            X             Y
0  Dunbar-Southlands  486111.0653  5.456088e+06
1  Dunbar-Southlands  485928.4343  5.455985e+06
2  Dunbar-Southlands  485939.5446  5.455985e+06
3  Dunbar-Southlands  485939.5446  5.455985e+06
4  Dunbar-Southlands  485939.5446  5.455985e+06

In [32]:
df

,TYPE,YEAR,MONTH,DAY,HOUR,MINUTE,HUNDRED_BLOCK,NEIGHBOURHOOD,X,Y
0,Theft from Vehicle,2022,3,17,21,0,39XX W 17TH AVE,Dunbar-Southlands,486111.0653,5.456088e+06
1,Theft from Vehicle,2010,4,29,20,30,39XX W 18TH AVE,Dunbar-Southlands,485928.4343,5.455985e+06
2,Theft from Vehicle,2003,12,23,23,0,39XX W 18TH AVE,Dunbar-Southlands,485939.5446,5.455985e+06
3,Theft from Vehicle,2004,6,15,19,0,39XX W 18TH AVE,Dunbar-Southlands,485939.5446,5.455985e+06
4,Theft from Vehicle,2004,6,16,22,0,39XX W 18TH AVE,Dunbar-Southlands,485939.5446,5.455985e+06
...,...,...,...,...,...,...,...,...,...,...
832086,Theft from Vehicle,2003,5,29,21,0,39XX W 17TH AVE,Dunbar-Southlands,486107.0294,5.456088e+06
832087,Theft from Vehicle,2013,7,31,19,0,39XX W 17TH AVE,Dunbar-Southlands,486107.0294,5.456088e+06
832088,Theft from Vehicle,2016,5,27,21,30,39XX W 17TH AVE,Dunbar-Southlands,486107.0294,5.456088e+06
832089,Theft from Vehicle,2019,6,4,18,0,39XX W 17TH AVE,Dunbar-Southlands,486107.0294,5.456088e+06
832090,Theft from Vehicle,2017,11,4,18,0,39XX W 17TH AVE,Dunbar-Southlands,486111.0653,5.456088e+06

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 832091 entries, 0 to 832090
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   TYPE           832091 non-null  object
 1   YEAR           832091 non-null  int64
 2   MONTH          832091 non-null  int64
 3   DAY            832091 non-null  int64
 4   HOUR           832091 non-null  int64
 5   MINUTE         832091 non-null  int64
 6   HUNDRED_BLOCK  832079 non-null  object
 7   NEIGHBOURHOOD  831953 non-null  object
 8   X              832019 non-null  float64
 9   Y              832019 non-null  float64
dtypes: float64(2), int64(5), object(3)
memory usage: 63.5+ MB

In [43]:
df.loc[df['TYPE']=='Theft from Vehicle']

,TYPE,YEAR,MONTH,DAY,HOUR,MINUTE,HUNDRED_BLOCK,NEIGHBOURHOOD,X,Y
0,Theft from Vehicle,2022,3,17,21,0,39XX W 17TH AVE,Dunbar-Southlands,486111.0653,5.456088e+06
1,Theft from Vehicle,2010,4,29,20,30,39XX W 18TH AVE,Dunbar-Southlands,485928.4343,5.455985e+06
2,Theft from Vehicle,2003,12,23,23,0,39XX W 18TH AVE,Dunbar-Southlands,485939.5446,5.455985e+06
3,Theft from Vehicle,2004,6,15,19,0,39XX W 18TH AVE,Dunbar-Southlands,485939.5446,5.455985e+06
4,Theft from Vehicle,2004,6,16,22,0,39XX W 18TH AVE,Dunbar-Southlands,485939.5446,5.455985e+06
...,...,...,...,...,...,...,...,...,...,...
832086,Theft from Vehicle,2003,5,29,21,0,39XX W 17TH AVE,Dunbar-Southlands,486107.0294,5.456088e+06
832087,Theft from Vehicle,2013,7,31,19,0,39XX W 17TH AVE,Dunbar-Southlands,486107.0294,5.456088e+06
832088,Theft from Vehicle,2016,5,27,21,30,39XX W 17TH AVE,Dunbar-Southlands,486107.0294,5.456088e+06
832089,Theft from Vehicle,2019,6,4,18,0,39XX W 17TH AVE,Dunbar-Southlands,486107.0294,5.456088e+06
832090,Theft from Vehicle,2017,11,4,18,0,39XX W 17TH AVE,Dunbar-Southlands,486111.0653,5.456088e+06

In [51]:
import pyproj

inProj = pyproj.Proj(init='epsg:3857')
outProj = pyproj.Proj(init='epsg:4326')

x1, y1 = (5.456088e+06,486111.0653)
x2, y2 = pyproj.transform(inProj, outProj, x1, y1)
print((x2, y2)) # wrong lat lng

(49.01287241901112, 4.3625885021847)

C:\Users\Sadia\anaconda3\lib\site-packages\pyproj\crs\crs.py:130: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)
C:\Users\Sadia\anaconda3\lib\site-packages\pyproj\crs\crs.py:130: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)
<ipython-input-51-ff9bd793c257>:7: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  x2, y2 = pyproj.transform(inProj, outProj, x1, y1)

In [45]:
!pip install pyproj

Collecting pyproj
  Downloading pyproj-3.3.1-cp38-cp38-win_amd64.whl (6.4 MB)
Requirement already satisfied: certifi in c:\users\sadia\anaconda3\lib\site-packages (from pyproj) (2020.6.20)
Installing collected packages: pyproj
Successfully installed pyproj-3.3.1